image: alpine:latest

pages:
  stage: deploy
  script:
    - echo "Deploying..."
    - mv public public-temp
    - mv public-temp/agni-app/build public
  artifacts:
    paths:
      - public
  tags:
    - Pages
  only:
    - main
